# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

# if the option no_tests was given, quit the script
if not env['no_examples']:
    
  # create the main executable
  env.Program(target = 'laplace_unstructured', source = "src/laplace_unstructured.cpp")
  env.Program(target = 'laplace_structured', source = "src/laplace_structured.cpp")
  env.Program(target = 'laplace_regular', source = "src/laplace_regular.cpp")
  env.Program(target = 'laplace_hermite', source = "src/laplace_hermite.cpp")
