# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

# define the source files
src_files = Split(
"""
  anisotropic_diffusion2d.cpp
""")

# create the main executable
env.Program(target = 'anisotropic_diffusion2d', source = src_files)
