# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

# create the main executable
env.Program(target = 'precontraction', source = "src/precontraction.cpp")
env.Program(target = 'precontraction_prestretch', source = "src/precontraction_prestretch.cpp")
env.Program(target = 'multidomain_prestretch', source = "src/multidomain_prestretch.cpp")
