# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

# if the option no_tests was given, quit the script
if not env['no_examples']:
      
  env.Program(target = 'generate_quadratic', source = "src/generate_quadratic.cpp")
  env.Program(target = 'generate', source = "src/generate.cpp")
  env.Program(target = 'scale', source = "src/scale.cpp")
  #env.Program(target = 'refine', source = "src/refine.cpp")
  #env.Program(target = 'fix', source = "src/fix.cpp")
