# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

env.Program(target = "fibers_emg", source = "src/fibers_emg.cpp")
env.Program(target = "fibers_shorten_emg", source = "src/fibers_shorten_emg.cpp")
#env.Program(target = "fibers_emg_2d_output", source = "src/fibers_emg_2d_output.cpp")
#env.Program(target = "fibers_linear_elasticity", source = "src/fibers_linear_elasticity.cpp")
#env.Program(target = "fibers_febio", source = "src/fibers_febio.cpp")
env.Program(target = "fast_fibers_emg", source = "src/fast_fibers_emg.cpp")
env.Program(target = "fast_fibers_shorten_emg", source = "src/fast_fibers_shorten_emg.cpp")
env.Program(target = "fast_fibers_shorten_emg_crank_nicolson", source = "src/fast_fibers_shorten_emg_crank_nicolson.cpp")
