# This is the top-level SConstruct file for opendihu core
#
# Usage: `scons BUILD_TYPE=debug` will build debug version, `scons` will build release version.


# read variables from user file 'config.py' and from command line arguments, e.g. `scons BUILD_TYPE=release`
vars = Variables('config.py', ARGUMENTS)

# specify type and default value for recognized variables
#vars.Add(BoolVariable('DUMMY', 'This is left in the code to see how bools work', 0))
vars.Add(EnumVariable('BUILD_TYPE', 'The build type, according to that different compiler options will be set. (Shortcuts: ''d'',''r'')',
                    'release', allowed_values=('debug', 'release'), ignorecase = 2, map={'d':'debug', 'r':'release'}))

# initialize environment object containing build system settings such as compilers and flags
# command line options are considered
env = Environment(variables = vars)

# check for unknown variables and output warning
unknown = vars.UnknownVariables()
if unknown:
  print "WARNING: Unknown variables from command line arguments or config file `config.py`:", unknown.keys()
    
# generate help text for the page `scons -h`
Help(vars.GenerateHelpText(env))

# -----------------------------------------------
# depending on the variable BUILD_TYPE either build with debug or release settings
if env["BUILD_TYPE"] == "debug":
  
  # debug build
  variant_dir = "build/debug"           # folder of build
  env.ParseFlags('-DDEBUG -ggdb -O0')   # gcc flags, will be sorted automatically into linker and compiler flags
  
else:
  # release build
  variant_dir = 'build/release'         # folder of build
  env.ParseFlags('-O3')   # gcc flags, will be sorted automatically into linker and compiler flags

# call SConscript file for the actual build in the specified build directory variant_dir
SConscript(dirs='.',
           variant_dir=variant_dir,
           duplicate=False,
           exports="env")
