# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

testcases = [
  "mooney_rivlin_incompressible_mixed",
  "mooney_rivlin_incompressible_mixed_condensation",
  "mooney_rivlin_incompressible_penalty",
]

testcases = ["mooney_rivlin_incompressible_mixed_condensation",]

for testcase in testcases:
  env.Program(target = testcase, source = "src/{}.cpp".format(testcase))
