# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

# create the main executable
env.Program(target = 'multidomain_with_fat', source = "src/multidomain_with_fat.cpp")
env.Program(target = 'multidomain_with_fat_emg', source = "src/multidomain_with_fat_emg.cpp")
env.Program(target = 'multidomain_shorten_with_fat', source = "src/multidomain_shorten_with_fat.cpp")
