# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

print("Note, you need to set VTK_DOWNLOAD=True as this needs vtk.")

env.Program(target = "extract_emg", source = "src/main.cpp")
