# This is the top-level SConscript file for the examples

# define all existing examples to be build
examples = [
  "build-test",
  "templates",
  "laplace1d",
  "laplace2d",
  "poisson1d",
  "poisson2d",
  "diffusion1d",
  "diffusion2d",
  "diffusion2d_2nd_order",
  "cellml",
  "electrophysiology",
]
# here the list is defined again with only a subset of the examples to save compilation time
examples = ["electrophysiology", "diffusion2d", "diffusion2d_2nd_order", "anisotropic_diffusion2d", "electrophysiology_anisotropic", "cellml"]
#examples = ["laplace1d"]
examples = []

# loop over examples and call SConstruct file
for example in examples:
  print("")
  print("example {}".format(example))
  SConscript(example+'/SConstruct')
