# This is the top-level SConscript file for the examples

# define all existing examples to be build
examples = [
  "build-test",
  "laplace1d",
  "laplace2d",
  "templates",
]
examples = ["diffusion1d"]

# loop over examples and call SConstruct file
for example in examples:
  print ""
  print "example",example
  SConscript(example+'/SConstruct')
