# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

# if the option no_tests was given, quit the script
if not env['no_examples']:
    
  examples = [
		"compressible_mooney_rivlin",
		"compressible_mooney_rivlin_decoupled",
    "incompressible_mooney_rivlin",
    "nearly_incompressible_mooney_rivlin",
    "nearly_incompressible_mooney_rivlin_decoupled",
    "linear",
    "nearly_incompressible_mooney_rivlin_febio"
  ]
  #examples = ["nearly_incompressible_mooney_rivlin_febio"]
  for example in examples:
    env.Program(target = example, source = "src/{}.cpp".format(example))

