# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

# if the option no_tests was given, quit the script
if not env['no_examples']:
    
  # define the source files
  src_files = [
    "diffusion_1d",
   # "diffusion_1d_pod",
  ]

  # create the main executable
  for src_file in src_files:
    env.Program(target = src_file, source = "src/{}.cpp".format(src_file))
