# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

# create the main executable
env.Program(target = 'tendon_dynamic', source = "src/tendon_dynamic.cpp")
env.Program(target = 'tendon_linear_dynamic', source = "src/tendon_linear_dynamic.cpp")
env.Program(target = 'tendon_linear_quasistatic', source = "src/tendon_linear_quasistatic.cpp")
env.Program(target = 'tendon_quasistatic', source = "src/tendon_quasistatic.cpp")
