# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

# define the source files
src_files = Split(
"""
  main.cpp
""")

# take the debug or release version of the opendihu library depending on build type
if env['BUILD_TYPE'] == "debug":
  libs = 'opendihud'
else:
  libs = 'opendihu'

# create the main executable
env.Program(target = 'build-test', source = src_files, LIBS=libs)
