#!/usr/bin/env python
# -*- coding: utf-8 -*-

#
# Script to print python output files in a readable format to stdout
#

import numpy as np
import scipy.integrate
import sys,os

import py_reader    # reader utility for opendihu *.py files

# output in a readable format
import pprint 
pp = pprint.PrettyPrinter()

files = ""

show_plot = True
if len(sys.argv) > 1:
  files = sys.argv[1:]
else:
  # get all input data in current directory
  ls = os.listdir(".")

  # sort files by number in file name
  files = sorted(ls)
  
# extract files
solution_py_condition = lambda filename: ".py" in filename
solution_py_files = list(np.extract(map(solution_py_condition, files), files))

print("{} files".format(len(solution_py_files)))
print(solution_py_files[0:min(10,len(solution_py_files))])

# load all files
data = py_reader.load_data(solution_py_files)

# loop over data files and output in readable formatting
for dataset in data:
  pp.pprint(dataset)
