# This script declares to SCons how to compile the example.
# It has to be called from a SConstruct file.
# The 'env' object is passed from there and contains further specification like directory and debug/release flags.
#
# Note: If you're creating a new example and copied this file, adjust the desired name of the executable in the 'target' parameter of env.Program.


Import('env')     # import Environment object from calling SConstruct

testcases = [
  "laplace_structured_linear",
  "laplace_structured_quadratic",
  "laplace_structured_hermite",
  "laplace_unstructured_linear",
  "laplace_unstructured_quadratic",
#  "laplace_unstructured_hermite",
]

#testcases = ["laplace_structured_linear"]
for testcase in testcases:
  env.Program(target = testcase, source = "src/{}.cpp".format(testcase))
