--[[ generated by MegaMol Configurator 1.2.0.0 --]]

--[[ 

Use this command line arguments to start MegaMol
in Cmd:
  -p "C:\git\project_files\adios_sphere.lua" -i Project_3 inst
in PowerShell:
  -p "C:\git\project_files\adios_sphere.lua" -i Project_3 inst

 --]]

mmCreateView("Project_3", "View3D", "v")
mmCreateModule("SimpleSphereRenderer", "::Project_3::rnd")
mmCreateModule("ADIOStoMultiParticle", "::Project_3::adiostomp")
mmCreateModule("adiosDataSource", "::Project_3::dat")
mmSetParamValue("::Project_3::dat::filename", "/store/software/opendihu/examples/electrophysiology/multiple_fibers/build_debug/out/fibers.bp")
mmCreateModule("OverrideParticleGlobals", "::Project_3::override")
mmSetParamValue("::Project_3::override::overrideRadius", "True")
mmSetParamValue("::Project_3::override::radius", "0.1")
mmCreateModule("LinearTransferFunction", "::Project_3::lt")
mmCreateCall("CallRender3D", "::Project_3::v::rendering", "::Project_3::rnd::rendering")
mmCreateCall("CallADIOSData", "::Project_3::adiostomp::adiosSlot", "::Project_3::dat::getdata")
mmCreateCall("MultiParticleDataCall", "::Project_3::override::indata", "::Project_3::adiostomp::mpSlot")
mmCreateCall("MultiParticleDataCall", "::Project_3::rnd::getdata", "::Project_3::override::outData")
mmCreateCall("CallGetTransferFunction", "::Project_3::rnd::gettransferfunction", "::Project_3::lt::gettransferfunction")
